POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "customer@gmail.com",
  "password": "Test1236"
}

###

POST http://localhost:5000/api/forgot-password
Content-Type: application/json

{
  "email": "customer@gmail.com",
  "password": "Test1236"
}

###

POST http://localhost:5000/api/update-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsImhhc2hlZFBhc3MiOiIkMmIkMDUkNXNOclo1Uzk2dVQyb2RUL1R2bi4yLm5WcTFDQ3BwUUNwdDBtNWlWeGgxcVJSblZVSFpaN2kiLCJpYXQiOjE2MDc4NzU0NTIsImV4cCI6MTYwNzg3NjM1Mn0.VM_x8-yKo7dtpRG04-jUgSMCwUtREcfQhCp3d244Djc"
}